name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: alaviss/setup-nim@master
        with:
          path: '../nim'
          version: 'version-1-4'
      - name: Run tests
        run: |
          export PATH=$HOME/.nimble/bin:$PATH
          nimble -y test
          nimble install -y
      - name: Build docs
        run: |
          export PATH=$HOME/.nimble/bin:$PATH
          nimble install hmisc
          nimble docgen
      - name: Publish docs
        uses: crazy-max/ghaction-github-pages@v1
        with:
          build_dir: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
