name:
  docgen
on:
  push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: alaviss/setup-nim@master
        with:
          path: '../nim'
          version: 'version-1-4'
      - run: "nimble -y install"
      - run: "nimble docgen"
      - uses: crazy-max/ghaction-github-pages@v1
        with:
          build_dir: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
