name:
  test
on:
  push
jobs:
  build:
    if: |
      !contains(github.event.head_commit.message, 'WIP')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: alaviss/setup-nim@master
        with:
          path: '../nim'
          version: 'version-1-4'
      - run: "nimble -y test && nimble install -y"
      - run: "nimble -y install nimble@0.13.0"
      - run: "nimble docgen"
      - uses: crazy-max/ghaction-github-pages@v1
        with:
          build_dir: htmldocs
          verbose: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
